### ISSUE TITLE
Link interfaces to their concrete implementations

### ISSUE THREAD

**Issue by c10b10** [EasyGraphQL/easygraphql-parser#9]
It would extremely useful to have another field that specifies what types implement a specific interface. You could use the `types` field that's currently just used for unions, or you could add a separate field. Currently there's no way to ascertain the link between a concrete and an abstract type from the generated data structure.

```
Employee: { 
   type: 'InterfaceTypeDefinition',
   description: undefined,
   fields: [ [Object], [Object], [Object] ],
   values: [],
   types: [],
   implementedTypes: [ 'SecurityGuard', 'Secretary' ]
},
```

**Comment by estrada9166** [comment]
@c10b10 Thanks for creating the issue, I just created a PR that will include a new field on the type that is going to be `implementedTypes : ['SecurityGuard']`, do you think this can be useful or you need exactly as you described it!

Thanks

**Comment by c10b10** [comment]
What you have added is useful in its own right, but what I am proposing is slightly different. To refer to your test cases what I would need is:

```
 it('should have types on interface', () => {
      expect(schema.User.implementedTypes).to.includes('Student')
      expect(schema.User.implementedTypes).to.includes('Teacher')
});
```

because often, we have things like:

```
Query {
  visitorsOnPage(pageId: String!): [User]
}
```

I'm generating data automatically for a certain schema, and this would allow me to map interfaces to concrete types automatically without having to walk the `parsedSchema` tree.

**Comment by estrada9166** [comment]
@c10b10 I'll work on that! 

>I'm generating data automatically for a certain schema

Also, have you check [easygraphql-mock](https://github.com/EasyGraphQL/easygraphql-mock) it'll create a mock of the schema...

**Comment by c10b10** [comment]
> I'll work on that!

Awesome!

> Also, have you check easygraphql-mock it'll create a mock of the schema...

I'm familiar with it. I appreciate all the effort you put in this suit of projects. I find them very helpful! Thank you!

**Comment by estrada9166** [comment]
> I'm familiar with it. I appreciate all the effort you put in this suit of projects. I find them very helpful! Thank you!

I'm really happy to read this :)

Also, sorry I didn't ask before, would you like to work on this PR?

**Comment by estrada9166** [comment]
@c10b10 just pushed the solution, let me know if I'm missing something :) #10

**Comment by c10b10** [comment]
This is perfect. Thank you so much!

When will you push a new version to npm?

**Comment by estrada9166** [comment]
@c10b10 there is a new version deployed!

Thanks for creating this issue :)
